<?php

namespace CDA\CertifBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

	/**
	 * Build request to retrieve all comments for a given work
	 *
	 * @param integer $workId
	 * @return array
	 */
	public function findCommentsWork($workId)
	{
		$qb = $this->createQueryBuilder('c')
		->join('c.work', 'w')
		->join('c.member', 'm')
		->addSelect('m')
		->andWhere('w.id = :work_id')
		->andWhere('w.isEnabled = TRUE')
		->setParameter('work_id', $workId);
	
		return $qb->getQuery()
		->getArrayResult();
	}
	
}